#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later

. /lib/functions.sh
. /usr/share/libubox/jshn.sh
. /usr/share/ModemManager/modemmanager.common

. /usr/lib/mm-watchdog/config.sh
. /usr/lib/mm-watchdog/webhook.sh
. /usr/lib/mm-watchdog/watchdog.sh

watchdog_main "$@"
