#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=10


start_service()
{
        local enabled

        config_load mm-watchdog
        config_get_bool enabled main enabled 1

        [ "$enabled" -eq 1 ] || return 0

        procd_open_instance

        procd_set_param command /usr/sbin/modem-watchdog

        #
        # Restart watchdog itself if it crashes.
        #
        procd_set_param respawn 3600 5 5

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}


service_triggers()
{
        procd_add_reload_trigger "mm-watchdog"
}