#!/bin/sh /etc/rc.common

# SPDX-License-Identifier: GPL-2.0-or-later

USE_PROCD=1

START=95
STOP=10
PROG=/usr/sbin/modem-watchdog

start_service() {
	local enabled=1

	config_load mm-watchdog
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance watchdog
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param reload_signal HUP
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	local enabled=1

	config_load mm-watchdog
	config_get_bool enabled main enabled 1

	if [ "$enabled" -eq 1 ]; then
		if service_running watchdog; then
			procd_send_signal mm-watchdog watchdog HUP
		else
			start
		fi
	else
		procd_kill mm-watchdog watchdog
	fi
}

service_triggers() {
	procd_add_reload_trigger mm-watchdog
}
